In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('/Users/apple/Projects/personal/python/Anaconda Lesson/data of pandas reading exercise /Customer Call List.xlsx')

In [3]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
type ('customer ID')

str

In [5]:
df = df.drop_duplicates()

In [6]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [7]:
df = df.drop(columns = "Not_Useful_Column" )

In [8]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [9]:
df["Last_Name"].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [10]:
df["Last_Name"].str.lstrip("...")

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [11]:
df["Last_Name"].str.lstrip("/")

0         Baggins
1           Nadir
2           White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [12]:
df["Last_Name"].str.lstrip(["/","..."])

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: Last_Name, dtype: float64

In [13]:
df["Last_Name"].str.lstrip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [14]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [36]:
df["Last_Name"]=df["Last_Name"].str.strip("...")

In [16]:
df["Last_Name"]

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [17]:
df["Last_Name"]=df["Last_Name"].str.strip("/")

In [18]:
df["Last_Name"]

0         Baggins
1           Nadir
2           White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [19]:
df["Last_Name"]=df["Last_Name"].str.rstrip("_")
# can also write like this _df["Last_Name"]=df["Last_Name"].str.strip("123._/")

In [20]:
df["Last_Name"]

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

In [21]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [37]:
df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

0     123--54-5-54
1     123--64-3-97
2     706--69-5-03
3     123--54-3-23
4     876--67-8-34
5     304--76-2-24
6             ----
7     876--67-8-34
8             ----
9     123--54-5-54
10            ----
11    706--69-5-03
12    123--54-3-23
13    876--67-8-34
14    304--76-2-24
15    123--54-5-54
16    123--64-3-97
17    706--69-5-03
18            ----
19    876--67-8-34
Name: Phone_Number, dtype: object

In [38]:
df["Phone_Number"] = df["Phone_Number"].astype(str).str.replace(r'[^0-9]', '', regex=True)

In [39]:
df["Phone_Number"]

0     12354554
1     12364397
2     70669503
3     12354323
4     87667834
5     30476224
6
7     87667834
8
9     12354554
10
11    70669503
12    12354323
13    87667834
14    30476224
15    12354554
16    12364397
17    70669503
18
19    87667834
Name: Phone_Number, dtype: object

In [40]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,12364397,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,70669503,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,12354323,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,30476224,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,70669503,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,12354323,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,87667834,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,70669503,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [29]:
df["Phone_Number"].apply(lambda x: str(x))
df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[0:3]+ '-' + x[3:6]+'-'+ x[6:10])

In [89]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [91]:
df["Phone_Number"]=df["Phone_Number"].str.replace('--','')

In [100]:
df["Phone_Number"]

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6
7     876-678-3469
8
9     123-545-5421
10
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18
19    876-678-3469
Name: Phone_Number, dtype: object

In [102]:
df["Last_Name"]=df["Last_Name"].str.replace('NaN','')
df["Last_Name"]

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

In [103]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [107]:
df["Address"].str.split(',',1, expand = True)

TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

In [31]:
df[["Street Address", "State", "Zip"]] = df["Address"].astype(str).str.split(',', n=2, expand=True)

In [32]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706--69-5-03,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,----,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,----,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,----,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706--69-5-03,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706--69-5-03,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,----,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [35]:
df["Phone_Number"].astype(str).replace('--','')

0     123--54-5-54
1     123--64-3-97
2     706--69-5-03
3     123--54-3-23
4     876--67-8-34
5     304--76-2-24
6             ----
7     876--67-8-34
8             ----
9     123--54-5-54
10            ----
11    706--69-5-03
12    123--54-3-23
13    876--67-8-34
14    304--76-2-24
15    123--54-5-54
16    123--64-3-97
17    706--69-5-03
18            ----
19    876--67-8-34
Name: Phone_Number, dtype: object

In [42]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[0:3]+ '-' + x[3:6]+'-'+ x[6:10])

In [43]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-97,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [46]:
df["Address"].astype(str).str.split(',',n=2, expand = True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [47]:
df[["Street Address", "State", "Zip"]] = df["Address"].astype(str).str.split(',',n=2, expand = True)

In [48]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-97,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [53]:
df["Paying Customer"]= df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"]=df["Paying Customer"].str.replace('No', 'N')

In [54]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-97,93 West Main Street,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [56]:
df["Do_Not_Contact"]= df["Do_Not_Contact"].str.replace('Yes', 'Y')
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace('No', 'N')

In [57]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [65]:
df = df.replace('N/a','')

In [66]:
df.replace('NaN','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-97,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,--,,,Y,,,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [67]:
df = df.fillna('')

In [68]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-97,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,--,,,Y,,,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [70]:
for x in df.index: 
    if df.loc[x, "Do_Not_Contact"] == 'Y':
         df.drop (x, inplace = True)

In [71]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [72]:
for x in df.index: 
    if df.loc[x, "Phone_Number"] == '':
         df.drop (x, inplace = True)

In [73]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [74]:
for x in df.index: 
    if df.loc[x, "Phone_Number"] == '--':
         df.drop (x, inplace = True)

In [75]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-03,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
11,1012,Harry,Potter,706-695-03,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-03,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [76]:
for x in df.index: 
    if df.loc[x, "Do_Not_Contact"] == '':
         df.drop (x, inplace = True)

In [77]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [78]:
df.reset_index()

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,4,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
2,7,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
3,9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
5,13,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
6,14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
7,15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,16,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,19,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [81]:
df = df.reset_index(drop = True)

In [82]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-34,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-34,98 Clue Drive,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-34,343 City Parkway,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [ ]:
df.dropna(subset="Phone_Number"), implace =True)