In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [4]:
page = requests.get (url)

In [5]:
soup =  BeautifulSoup(page.text,'html')

In [6]:
print (soup)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [7]:
soup.find('div')

<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>

In [8]:
soup.find_all('div')

[<div class="container">
 <div class="col-md-12">
 <ul class="nav nav-tabs">
 <li id="nav-homepage">
 <a class="nav-link hidden-sm hidden-xs" href="/">
 <img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                 Scrape This Site
                             </a>
 </li>
 <li id="nav-sandbox">
 <a class="nav-link" href="/pages/">
 <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                 Sandbox
                             </a>
 </li>
 <li id="nav-lessons">
 <a class="nav-link" href="/lessons/">
 <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                 Lessons
                             </a>
 </li>
 <li id="nav-faq">
 <a class="nav-link" href="/faq/">
 <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                 FAQ
                             </a>
 </li>
 <li class="pull-right" id="nav-login">
 <a class="nav-link" href="/login/">
                                 Login
                             </a>
 </li>
 </ul>
 </div>
 </div>,
 <div class="col-md-12">
 <ul class="nav nav-tabs">
 <li id="nav-homepage">
 <a class="nav-link hidden-sm hidden-xs" href="/">
 <img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                 Scrape This Site
                             </a>
 </li>
 <li id="nav-sandbox">
 <a class="nav-link" href="/pages/">
 <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                 Sandbox
                             </a>
 </li>
 <li id="nav-lessons">
 <a class="nav-link" href="/lessons/">
 <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                 Lessons
                             </a>
 </li>
 <li id="nav-faq">
 <a class="nav-link" href="/faq/">
 <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                 FAQ
                             </a>
 </li>
 <li class="pull-right" id="nav-login">
 <a class="nav-link" href="/login/">
                                 Login
                             </a>
 </li>
 </ul>
 </div>,
 <div id="page">
 <section id="hockey">
 <div class="container">
 <div class="row">
 <div class="col-md-12">
 <h1>
                             Hockey Teams: Forms, Searching and Pagination
                             <small>25 items</small>
 </h1>
 <hr/>
 </div>
 </div>
 <div class="row">
 <div class="col-md-12">
 <p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>
 <hr/>
 </div>
 </div>
 <div class="row">
 <div class="col-md-6">
 <p>
 <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                         </p>
 <hr/>
 </div>
 <div class="col-md-6 text-right">
 <p>

                                 Data via
                                 <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
 </p>
 <hr/>
 </div>
 </div>
 <div class="row search-area">
 <div class="col-md-12 text-center">
 <form action="/pages/forms/" class="form form-inline" method="GET">
 <label for="q">
                                 Search for Teams:
                             </label>
 <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
 <input class="btn btn-primary" type="submit" value="Search"/>
 </form>
 <hr/>
 </div>
 </div><!--.row.search-area-->
 <table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>

In [12]:
soup.find_all('team')

[]

In [13]:
soup.find_all('education')

[]

In [14]:
soup.find_all('p')

[<p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>,
 <p>
 <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                         </p>,
 <p>

                                 Data via
                                 <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
 </p>]

In [15]:
soup.find_all('class')

[]

In [16]:
soup.find_all('p', class_= 'lead')

[<p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>]

In [17]:
soup.find_all('p', class_= 'lead').text

AttributeError: ResultSet object has no attribute "text". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [24]:
soup.find ('p', class_ = 'lead').text.strip()

'Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.'

In [26]:
soup.find_all('th')

[<th>
                             Team Name
                         </th>,
 <th>
                             Year
                         </th>,
 <th>
                             Wins
                         </th>,
 <th>
                             Losses
                         </th>,
 <th>
                             OT Losses
                         </th>,
 <th>
                             Win %
                         </th>,
 <th>
                             Goals For (GF)
                         </th>,
 <th>
                             Goals Against (GA)
                         </th>,
 <th>
                             + / -
                         </th>]

In [27]:
soup.find_all('td')

[<td class="name">
                             Boston Bruins
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             44
                         </td>,
 <td class="losses">
                             24
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.55
                         </td>,
 <td class="gf">
                             299
                         </td>,
 <td class="ga">
                             264
                         </td>,
 <td class="diff text-success">
                             35
                         </td>,
 <td class="name">
                             Buffalo Sabres
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             30
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             292
                         </td>,
 <td class="ga">
                             278
                         </td>,
 <td class="diff text-success">
                             14
                         </td>,
 <td class="name">
                             Calgary Flames
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             46
                         </td>,
 <td class="losses">
                             26
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.575
                         </td>,
 <td class="gf">
                             344
                         </td>,
 <td class="ga">
                             263
                         </td>,
 <td class="diff text-success">
                             81
                         </td>,
 <td class="name">
                             Chicago Blackhawks
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             49
                         </td>,
 <td class="losses">
                             23
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.613
                         </td>,
 <td class="gf">
                             284
                         </td>,
 <td class="ga">
                             211
                         </td>,
 <td class="diff text-success">
                             73
                         </td>,
 <td class="name">
                             Detroit Red Wings
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             34
                         </td>,
 <td class="losses">
                             38
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.425
                         </td>,
 <td class="gf">
                             273
                         </td>,
 <td class="ga">
                             298
                         </td>,
 <td class="diff text-danger">
                             -25
                         </td>,
 <td class="name">
                             Edmonton Oilers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             37
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.463
                         </td>,
 <td class="gf">
                             272
                         </td>,
 <td class="ga">
                             272
                         </td>,
 <td class="diff text-success">
                             0
                         </td>,
 <td class="name">
                             Hartford Whalers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             38
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             238
                         </td>,
 <td class="ga">
                             276
                         </td>,
 <td class="diff text-danger">
                             -38
                         </td>,
 <td class="name">
                             Los Angeles Kings
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             46
                         </td>,
 <td class="losses">
                             24
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.575
                         </td>,
 <td class="gf">
                             340
                         </td>,
 <td class="ga">
                             254
                         </td>,
 <td class="diff text-success">
                             86
                         </td>,
 <td class="name">
                             Minnesota North Stars
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             27
                         </td>,
 <td class="losses">
                             39
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.338
                         </td>,
 <td class="gf">
                             256
                         </td>,
 <td class="ga">
                             266
                         </td>,
 <td class="diff text-danger">
                             -10
                         </td>,
 <td class="name">
                             Montreal Canadiens
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             39
                         </td>,
 <td class="losses">
                             30
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.487
                         </td>,
 <td class="gf">
                             273
                         </td>,
 <td class="ga">
                             249
                         </td>,
 <td class="diff text-success">
                             24
                         </td>,
 <td class="name">
                             New Jersey Devils
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             32
                         </td>,
 <td class="losses">
                             33
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.4
                         </td>,
 <td class="gf">
                             272
                         </td>,
 <td class="ga">
                             264
                         </td>,
 <td class="diff text-success">
                             8
                         </td>,
 <td class="name">
                             New York Islanders
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             25
                         </td>,
 <td class="losses">
                             45
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.312
                         </td>,
 <td class="gf">
                             223
                         </td>,
 <td class="ga">
                             290
                         </td>,
 <td class="diff text-danger">
                             -67
                         </td>,
 <td class="name">
                             New York Rangers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             31
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             297
                         </td>,
 <td class="ga">
                             265
                         </td>,
 <td class="diff text-success">
                             32
                         </td>,
 <td class="name">
                             Philadelphia Flyers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             33
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.412
                         </td>,
 <td class="gf">
                             252
                         </td>,
 <td class="ga">
                             267
                         </td>,
 <td class="diff text-danger">
                             -15
                         </td>,
 <td class="name">
                             Pittsburgh Penguins
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             41
                         </td>,
 <td class="losses">
                             33
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.512
                         </td>,
 <td class="gf">
                             342
                         </td>,
 <td class="ga">
                             305
                         </td>,
 <td class="diff text-success">
                             37
                         </td>,
 <td class="name">
                             Quebec Nordiques
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             16
                         </td>,
 <td class="losses">
                             50
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.2
                         </td>,
 <td class="gf">
                             236
                         </td>,
 <td class="ga">
                             354
                         </td>,
 <td class="diff text-danger">
                             -118
                         </td>,
 <td class="name">
                             St. Louis Blues
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             47
                         </td>,
 <td class="losses">
                             22
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.588
                         </td>,
 <td class="gf">
                             310
                         </td>,
 <td class="ga">
                             250
                         </td>,
 <td class="diff text-success">
                             60
                         </td>,
 <td class="name">
                             Toronto Maple Leafs
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             23
                         </td>,
 <td class="losses">
                             46
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.287
                         </td>,
 <td class="gf">
                             241
                         </td>,
 <td class="ga">
                             318
                         </td>,
 <td class="diff text-danger">
                             -77
                         </td>,
 <td class="name">
                             Vancouver Canucks
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             28
                         </td>,
 <td class="losses">
                             43
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.35
                         </td>,
 <td class="gf">
                             243
                         </td>,
 <td class="ga">
                             315
                         </td>,
 <td class="diff text-danger">
                             -72
                         </td>,
 <td class="name">
                             Washington Capitals
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             37
                         </td>,
 <td class="losses">
                             36
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.463
                         </td>,
 <td class="gf">
                             258
                         </td>,
 <td class="ga">
                             258
                         </td>,
 <td class="diff text-success">
                             0
                         </td>,
 <td class="name">
                             Winnipeg Jets
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             26
                         </td>,
 <td class="losses">
                             43
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.325
                         </td>,
 <td class="gf">
                             260
                         </td>,
 <td class="ga">
                             288
                         </td>,
 <td class="diff text-danger">
                             -28
                         </td>,
 <td class="name">
                             Boston Bruins
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             32
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             270
                         </td>,
 <td class="ga">
                             275
                         </td>,
 <td class="diff text-danger">
                             -5
                         </td>,
 <td class="name">
                             Buffalo Sabres
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             289
                         </td>,
 <td class="ga">
                             299
                         </td>,
 <td class="diff text-danger">
                             -10
                         </td>,
 <td class="name">
                             Calgary Flames
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             296
                         </td>,
 <td class="ga">
                             305
                         </td>,
 <td class="diff text-danger">
                             -9
                         </td>,
 <td class="name">
                             Chicago Blackhawks
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             29
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             257
                         </td>,
 <td class="ga">
                             236
                         </td>,
 <td class="diff text-success">
                             21
                         </td>]

In [28]:
soup.find('th').text.strip()

'Team Name'

In [29]:
soup.find_all('tr')

[<tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>,
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             260
                         </td>
 <td class="ga">
                             288
                         </td>
 <td class="diff text-danger">
                             -28
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             270
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-danger">
                             -5
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             296
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             257
                         </td>
 <td class="ga">
                             236
                         </td>
 <td class="diff text-success">
                             21
                         </td>
 </tr>]

In [30]:
soup.find('tr').text.strip()

'Team Name\n                        \n\n                            Year\n                        \n\n                            Wins\n                        \n\n                            Losses\n                        \n\n                            OT Losses\n                        \n\n                            Win %\n                        \n\n                            Goals For (GF)\n                        \n\n                            Goals Against (GA)\n                        \n\n                            + / -'

In [31]:
soup.find_all('td')

[<td class="name">
                             Boston Bruins
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             44
                         </td>,
 <td class="losses">
                             24
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.55
                         </td>,
 <td class="gf">
                             299
                         </td>,
 <td class="ga">
                             264
                         </td>,
 <td class="diff text-success">
                             35
                         </td>,
 <td class="name">
                             Buffalo Sabres
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             30
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             292
                         </td>,
 <td class="ga">
                             278
                         </td>,
 <td class="diff text-success">
                             14
                         </td>,
 <td class="name">
                             Calgary Flames
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             46
                         </td>,
 <td class="losses">
                             26
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.575
                         </td>,
 <td class="gf">
                             344
                         </td>,
 <td class="ga">
                             263
                         </td>,
 <td class="diff text-success">
                             81
                         </td>,
 <td class="name">
                             Chicago Blackhawks
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             49
                         </td>,
 <td class="losses">
                             23
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.613
                         </td>,
 <td class="gf">
                             284
                         </td>,
 <td class="ga">
                             211
                         </td>,
 <td class="diff text-success">
                             73
                         </td>,
 <td class="name">
                             Detroit Red Wings
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             34
                         </td>,
 <td class="losses">
                             38
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.425
                         </td>,
 <td class="gf">
                             273
                         </td>,
 <td class="ga">
                             298
                         </td>,
 <td class="diff text-danger">
                             -25
                         </td>,
 <td class="name">
                             Edmonton Oilers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             37
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.463
                         </td>,
 <td class="gf">
                             272
                         </td>,
 <td class="ga">
                             272
                         </td>,
 <td class="diff text-success">
                             0
                         </td>,
 <td class="name">
                             Hartford Whalers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             38
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             238
                         </td>,
 <td class="ga">
                             276
                         </td>,
 <td class="diff text-danger">
                             -38
                         </td>,
 <td class="name">
                             Los Angeles Kings
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             46
                         </td>,
 <td class="losses">
                             24
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.575
                         </td>,
 <td class="gf">
                             340
                         </td>,
 <td class="ga">
                             254
                         </td>,
 <td class="diff text-success">
                             86
                         </td>,
 <td class="name">
                             Minnesota North Stars
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             27
                         </td>,
 <td class="losses">
                             39
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.338
                         </td>,
 <td class="gf">
                             256
                         </td>,
 <td class="ga">
                             266
                         </td>,
 <td class="diff text-danger">
                             -10
                         </td>,
 <td class="name">
                             Montreal Canadiens
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             39
                         </td>,
 <td class="losses">
                             30
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.487
                         </td>,
 <td class="gf">
                             273
                         </td>,
 <td class="ga">
                             249
                         </td>,
 <td class="diff text-success">
                             24
                         </td>,
 <td class="name">
                             New Jersey Devils
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             32
                         </td>,
 <td class="losses">
                             33
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.4
                         </td>,
 <td class="gf">
                             272
                         </td>,
 <td class="ga">
                             264
                         </td>,
 <td class="diff text-success">
                             8
                         </td>,
 <td class="name">
                             New York Islanders
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             25
                         </td>,
 <td class="losses">
                             45
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.312
                         </td>,
 <td class="gf">
                             223
                         </td>,
 <td class="ga">
                             290
                         </td>,
 <td class="diff text-danger">
                             -67
                         </td>,
 <td class="name">
                             New York Rangers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             31
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             297
                         </td>,
 <td class="ga">
                             265
                         </td>,
 <td class="diff text-success">
                             32
                         </td>,
 <td class="name">
                             Philadelphia Flyers
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             33
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.412
                         </td>,
 <td class="gf">
                             252
                         </td>,
 <td class="ga">
                             267
                         </td>,
 <td class="diff text-danger">
                             -15
                         </td>,
 <td class="name">
                             Pittsburgh Penguins
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             41
                         </td>,
 <td class="losses">
                             33
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.512
                         </td>,
 <td class="gf">
                             342
                         </td>,
 <td class="ga">
                             305
                         </td>,
 <td class="diff text-success">
                             37
                         </td>,
 <td class="name">
                             Quebec Nordiques
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             16
                         </td>,
 <td class="losses">
                             50
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.2
                         </td>,
 <td class="gf">
                             236
                         </td>,
 <td class="ga">
                             354
                         </td>,
 <td class="diff text-danger">
                             -118
                         </td>,
 <td class="name">
                             St. Louis Blues
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             47
                         </td>,
 <td class="losses">
                             22
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.588
                         </td>,
 <td class="gf">
                             310
                         </td>,
 <td class="ga">
                             250
                         </td>,
 <td class="diff text-success">
                             60
                         </td>,
 <td class="name">
                             Toronto Maple Leafs
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             23
                         </td>,
 <td class="losses">
                             46
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.287
                         </td>,
 <td class="gf">
                             241
                         </td>,
 <td class="ga">
                             318
                         </td>,
 <td class="diff text-danger">
                             -77
                         </td>,
 <td class="name">
                             Vancouver Canucks
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             28
                         </td>,
 <td class="losses">
                             43
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.35
                         </td>,
 <td class="gf">
                             243
                         </td>,
 <td class="ga">
                             315
                         </td>,
 <td class="diff text-danger">
                             -72
                         </td>,
 <td class="name">
                             Washington Capitals
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             37
                         </td>,
 <td class="losses">
                             36
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.463
                         </td>,
 <td class="gf">
                             258
                         </td>,
 <td class="ga">
                             258
                         </td>,
 <td class="diff text-success">
                             0
                         </td>,
 <td class="name">
                             Winnipeg Jets
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             26
                         </td>,
 <td class="losses">
                             43
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.325
                         </td>,
 <td class="gf">
                             260
                         </td>,
 <td class="ga">
                             288
                         </td>,
 <td class="diff text-danger">
                             -28
                         </td>,
 <td class="name">
                             Boston Bruins
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             32
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             270
                         </td>,
 <td class="ga">
                             275
                         </td>,
 <td class="diff text-danger">
                             -5
                         </td>,
 <td class="name">
                             Buffalo Sabres
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             289
                         </td>,
 <td class="ga">
                             299
                         </td>,
 <td class="diff text-danger">
                             -10
                         </td>,
 <td class="name">
                             Calgary Flames
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             31
                         </td>,
 <td class="losses">
                             37
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.388
                         </td>,
 <td class="gf">
                             296
                         </td>,
 <td class="ga">
                             305
                         </td>,
 <td class="diff text-danger">
                             -9
                         </td>,
 <td class="name">
                             Chicago Blackhawks
                         </td>,
 <td class="year">
                             1991
                         </td>,
 <td class="wins">
                             36
                         </td>,
 <td class="losses">
                             29
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-danger">
                             0.45
                         </td>,
 <td class="gf">
                             257
                         </td>,
 <td class="ga">
                             236
                         </td>,
 <td class="diff text-success">
                             21
                         </td>]

In [33]:
soup.find('td').text.strip()

'Boston Bruins'

###Scrape and Pandas

In [34]:
from bs4 import BeautifulSoup
import requests

In [37]:
url= 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

In [38]:
page = requests.get(url)

In [39]:
soup= BeautifulSoup(page.text,'html')

In [40]:
print (soup)

<html><body><p>Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.
</p></body></html>

In [41]:
print (soup)

<html><body><p>Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.
</p></body></html>

In [46]:
soup.find_all('table' class =)

SyntaxError: invalid syntax (2422782661.py, line 1)

In [ ]:
<table class="wikitable sortable jquery-tablesorter" id="mwOw">
<caption id="mwPA"></caption>

In [47]:
from bs4 import BeautifulSoup
import requests

In [48]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [57]:
print(soup)

<html><body><p>Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.
</p></body></html>

In [54]:
soup.find('table', class_ = 'wikitable sortable')

In [55]:
table = soup.find_all('table')

In [56]:
print(table)

[]

In [58]:
from bs4 import BeautifulSoup
import requests

In [59]:
url = 'https://ait.ac.th/program/development-innovation-and-sustainability-dis/'

In [60]:
page = requests.get(url)

In [61]:
soup = BeautifulSoup(page.text, 'html')

In [62]:
print(soup)

<!DOCTYPE html>
<html><head> <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-103260356-1"></script> <script>window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());
		gtag('config', 'UA-103260356-1');</script> <meta content="ie=edge" http-equiv="x-ua-compatible"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta charset="utf-8"/><meta content="width=device-width, initial-scale=1" name="viewport"/><link href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/><link href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/><link href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/><link href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/site.webmanifest" rel="manifest"/><link color="#28393e" href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/safari-pinned-tab.svg" rel="mask-icon"/><link href="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/favicon.ico" rel="shortcut icon"/><meta content="#28393e" name="msapplication-TileColor"/><meta content="https://ait.ac.th/wp-content/themes/ait2026/build/images/favicons/browserconfig.xml" name="msapplication-config"/><meta content="#ffffff" name="theme-color"/><link href="https://fonts.googleapis.com" rel="preconnect"/><title>Development Innovation and Sustainability (DIS) - Asian Institute of Technology</title><meta content="Development Innovation and Sustainability (DIS) - Asian Institute of Technology" name="dc.title"/><meta content="Introduction / Background The Development Innovation and Sustainability (DIS) academic program is a consolidated and forward-looking initiative of the Asian Institute of Technology (AIT), developed in response to increasingly complex development challenges in Asia and beyond. It integrates the strengths of two established programs—Development Planning, Management and Innovation (DPMI) and…" name="dc.description"/><meta content="https://ait.ac.th/program/development-innovation-and-sustainability-dis/" name="dc.relation"/><meta content="https://ait.ac.th/" name="dc.source"/><meta content="en_US" name="dc.language"/><meta content="Introduction / Background The Development Innovation and Sustainability (DIS) academic program is a consolidated and forward-looking initiative of the Asian Institute of Technology (AIT), developed in response to increasingly complex development challenges in Asia and beyond. It integrates the strengths of two established programs—Development Planning, Management and Innovation (DPMI) and…" name="description"/><meta content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/><link href="https://ait.ac.th/program/development-innovation-and-sustainability-dis/" rel="canonical"/><meta content="https://ait.ac.th/program/development-innovation-and-sustainability-dis/" property="og:url"/><meta content="Asian Institute of Technology" property="og:site_name"/><meta content="en_US" property="og:locale"/><meta content="article" property="og:type"/><meta content="https://www.facebook.com/AITasia/" property="article:author"/><meta content="https://www.facebook.com/AITasia/" property="article:publisher"/><meta content="Development Innovation and Sustainability (DIS) - Asian Institute of Technology" property="og:title"/><meta content="Introduction / Background The Development Innovation and Sustainability (DIS) academic program is a consolidated and forward-looking initiative of the Asian Institute of Technology (AIT), developed in response to increasingly complex development challenges in Asia and beyond. It integrates the strengths of two established programs—Development Planning, Management and Innovation (DPMI) and…" property="og:description"/><meta content="https://ait.ac.th/wp-content/uploads/2022/01/01-DS_01-scaled.jpg" property="og:image"/><meta content="https://ait.ac.th/wp-content/uploads/2022/01/01-DS_01-scaled.jpg" property="og:image:secure_url"/><meta content="2560" property="og:image:width"/><meta content="1707" property="og:image:height"/><meta content="" property="fb:pages"/><meta content="" property="fb:app_id"/><meta content="summary" name="twitter:card"/><meta content="@aitasia" name="twitter:site"/><meta content="@aitasia" name="twitter:creator"/><meta content="Development Innovation and Sustainability (DIS) - Asian Institute of Technology" name="twitter:title"/><meta content="Introduction / Background The Development Innovation and Sustainability (DIS) academic program is a consolidated and forward-looking initiative of the Asian Institute of Technology (AIT), developed in response to increasingly complex development challenges in Asia and beyond. It integrates the strengths of two established programs—Development Planning, Management and Innovation (DPMI) and…" name="twitter:description"/><meta content="https://ait.ac.th/wp-content/uploads/2022/01/01-DS_01-scaled.jpg" name="twitter:image"/><link href="https://ait.ac.th/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fait.ac.th%2Fprogram%2Fdevelopment-innovation-and-sustainability-dis%2F" rel="alternate" title="oEmbed (JSON)" type="application/json+oembed"/><link href="https://ait.ac.th/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fait.ac.th%2Fprogram%2Fdevelopment-innovation-and-sustainability-dis%2F&amp;format=xml" rel="alternate" title="oEmbed (XML)" type="text/xml+oembed"/><style id="wp-img-auto-sizes-contain-inline-css">img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}
/*# sourceURL=wp-img-auto-sizes-contain-inline-css */</style><style id="classic-theme-styles-inline-css">/*! This file is auto-generated */
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}
/*# sourceURL=/wp-includes/css/classic-themes.min.css */</style><style id="global-styles-inline-css">:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgb(6,147,227) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgb(252,185,0) 0%,rgb(255,105,0) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgb(255,105,0) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgb(255, 255, 255), 6px 6px rgb(0, 0, 0);--wp--preset--shadow--crisp: 6px 6px 0px rgb(0, 0, 0);}:where(body) { margin: 0; }:where(.is-layout-flex){gap: 0.5em;}:where(.is-layout-grid){gap: 0.5em;}body .is-layout-flex{display: flex;}.is-layout-flex{flex-wrap: wrap;align-items: center;}.is-layout-flex > :is(*, div){margin: 0;}body .is-layout-grid{display: grid;}.is-layout-grid > :is(*, div){margin: 0;}body{padding-top: 0px;padding-right: 0px;padding-bottom: 0px;padding-left: 0px;}:root :where(.wp-element-button, .wp-block-button__link){background-color: #32373c;border-width: 0;color: #fff;font-family: inherit;font-size: inherit;font-style: inherit;font-weight: inherit;letter-spacing: inherit;line-height: inherit;padding-top: calc(0.667em + 2px);padding-right: calc(1.333em + 2px);padding-bottom: calc(0.667em + 2px);padding-left: calc(1.333em + 2px);text-decoration: none;text-transform: inherit;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}
/*# sourceURL=global-styles-inline-css */</style> <script id="jquery-js" src="https://ait.ac.th/wp-includes/js/jquery/jquery.js"></script> <script id="cookie-law-info-js-extra">var Cli_Data = {"nn_cookie_ids":[],"cookielist":[],"non_necessary_cookies":[],"ccpaEnabled":"","ccpaRegionBased":"","ccpaBarEnabled":"","strictlyEnabled":["necessary","obligatoire"],"ccpaType":"gdpr","js_blocking":"1","custom_integration":"","triggerDomRefresh":"","secure_cookies":""};
var cli_cookiebar_settings = {"animate_speed_hide":"500","animate_speed_show":"500","background":"#FFF","border":"#b1a6a6c2","border_on":"","button_1_button_colour":"#61a229","button_1_button_hover":"#4e8221","button_1_link_colour":"#fff","button_1_as_button":"1","button_1_new_win":"","button_2_button_colour":"#333","button_2_button_hover":"#292929","button_2_link_colour":"#444","button_2_as_button":"","button_2_hidebar":"","button_3_button_colour":"#dedfe0","button_3_button_hover":"#b2b2b3","button_3_link_colour":"#333333","button_3_as_button":"1","button_3_new_win":"","button_4_button_colour":"#dedfe0","button_4_button_hover":"#b2b2b3","button_4_link_colour":"#333333","button_4_as_button":"1","button_7_button_colour":"#61a229","button_7_button_hover":"#4e8221","button_7_link_colour":"#fff","button_7_as_button":"1","button_7_new_win":"","font_family":"inherit","header_fix":"","notify_animate_hide":"1","notify_animate_show":"","notify_div_id":"#cookie-law-info-bar","notify_position_horizontal":"right","notify_position_vertical":"bottom","scroll_close":"","scroll_close_reload":"","accept_close_reload":"","reject_close_reload":"","showagain_tab":"","showagain_background":"#fff","showagain_border":"#000","showagain_div_id":"#cookie-law-info-again","showagain_x_position":"100px","text":"#333333","show_once_yn":"","show_once":"10000","logging_on":"","as_popup":"","popup_overlay":"1","bar_heading_text":"","cookie_bar_as":"banner","popup_showagain_position":"bottom-right","widget_position":"left"};
var log_object = {"ajax_url":"https://ait.ac.th/wp-admin/admin-ajax.php"};
//# sourceURL=cookie-law-info-js-extra</script> <script id="cookie-law-info-js" src="https://ait.ac.th/wp-content/plugins/cookie-law-info/legacy/public/js/cookie-law-info-public.js"></script> <link href="https://ait.ac.th/wp-json/" rel="https://api.w.org/"/><link href="https://ait.ac.th/wp-json/wp/v2/program/45434" rel="alternate" title="JSON" type="application/json"/> <script>(function ($) {
            $(document).on('facetwp-loaded', function () {
                if (FWP.loaded) {
                    $('html, body').animate({
                        scrollTop: $('.facetwp-template').offset().top
                    }, 500);
                }
            });
        })(jQuery);</script> <style id="wp-block-heading-inline-css">h1:where(.wp-block-heading).has-background,h2:where(.wp-block-heading).has-background,h3:where(.wp-block-heading).has-background,h4:where(.wp-block-heading).has-background,h5:where(.wp-block-heading).has-background,h6:where(.wp-block-heading).has-background{padding:1.25em 2.375em}h1.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h1.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h2.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h2.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h3.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h3.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h4.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h4.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h5.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h5.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h6.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h6.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]){rotate:180deg}
/*# sourceURL=https://ait.ac.th/wp-includes/blocks/heading/style.min.css */</style><style id="wp-block-list-inline-css">ol,ul{box-sizing:border-box}:root :where(.wp-block-list.has-background){padding:1.25em 2.375em}

In [66]:
soup.find_all('h2', class_= "wp-block-heading" )

[<h2 class="wp-block-heading">Introduction / Background</h2>,
 <h2 class="wp-block-heading">Areas of Specialization</h2>,
 <h2 class="wp-block-heading">Focus Areas</h2>,
 <h2 class="wp-block-heading">Preferred Background</h2>,
 <h2 class="wp-block-heading">Course Structure</h2>,
 <h2 class="wp-block-heading">Contact Information</h2>]

In [67]:
soup.find('h2', class_= "wp-block-heading" ).text

'Introduction / Background'

In [119]:
from bs4 import BeautifulSoup
import requests

In [120]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [121]:
page = requests.get(url)

In [122]:
soup = BeautifulSoup (page.text,'html')

In [123]:
print(soup)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [124]:
soup.find('table')

<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.325
                        </td>
<td class="gf">
                            260
                        </td>
<td class="ga">
                            288
                        </td>
<td class="diff text-danger">
                            -28
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            270
                        </td>
<td class="ga">
                            275
                        </td>
<td class="diff text-danger">
                            -5
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            289
                        </td>
<td class="ga">
                            299
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            296
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-danger">
                            -9
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            29
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            257
                        </td>
<td class="ga">
                            236
                        </td>
<td class="diff text-success">
                            21
                        </td>
</tr>
</table>

In [74]:
soup.find_all('table')

[<table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             260
                         </td>
 <td class="ga">
                             288
                         </td>
 <td class="diff text-danger">
                             -28
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             270
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-danger">
                             -5
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             296
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             257
                         </td>
 <td class="ga">
                             236
                         </td>
 <td class="diff text-success">
                             21
                         </td>
 </tr>
 </table>]

In [125]:
soup.find('table', class_ = 'table ')

In [126]:
print ('table')

table

In [127]:
soup.find('th')

<th>
                            Team Name
                        </th>

In [128]:
soup.find('td')

<td class="name">
                            Boston Bruins
                        </td>

In [ ]:
<table class="table">
    <tbody>
        <tr>
            <th>
                                        Team Name
                                    </th>
            <th>
                                        Year
                                    </th>
            <th>
                                        Wins
                                    </th>
            <th>
                                        Losses
                                    </th>
            <th>
                                        OT Losses
                                    </th>
            <th>
                                        Win %
                                    </th>
            <th>
                                        Goals For (GF)
                                    </th>
            <th>
                                        Goals Against (GA)
                                    </th>
            <th>
                                        + / -
                                    </th>
        </tr>

        <tr class="team">
            <td class="name">
                                        Boston Bruins
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        44
                                    </td>
            <td class="losses">
                                        24
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.55
                                    </td>

            <td class="gf">
                                        299
                                    </td>
            <td class="ga">
                                        264
                                    </td>

            <td class="diff text-success">
                                        35
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Buffalo Sabres
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        31
                                    </td>
            <td class="losses">
                                        30
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.388
                                    </td>

            <td class="gf">
                                        292
                                    </td>
            <td class="ga">
                                        278
                                    </td>

            <td class="diff text-success">
                                        14
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Calgary Flames
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        46
                                    </td>
            <td class="losses">
                                        26
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.575
                                    </td>

            <td class="gf">
                                        344
                                    </td>
            <td class="ga">
                                        263
                                    </td>

            <td class="diff text-success">
                                        81
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Chicago Blackhawks
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        49
                                    </td>
            <td class="losses">
                                        23
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.613
                                    </td>

            <td class="gf">
                                        284
                                    </td>
            <td class="ga">
                                        211
                                    </td>

            <td class="diff text-success">
                                        73
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Detroit Red Wings
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        34
                                    </td>
            <td class="losses">
                                        38
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.425
                                    </td>

            <td class="gf">
                                        273
                                    </td>
            <td class="ga">
                                        298
                                    </td>

            <td class="diff text-danger">
                                        -25
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Edmonton Oilers
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        37
                                    </td>
            <td class="losses">
                                        37
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.463
                                    </td>

            <td class="gf">
                                        272
                                    </td>
            <td class="ga">
                                        272
                                    </td>

            <td class="diff text-success">
                                        0
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Hartford Whalers
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        31
                                    </td>
            <td class="losses">
                                        38
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.388
                                    </td>

            <td class="gf">
                                        238
                                    </td>
            <td class="ga">
                                        276
                                    </td>

            <td class="diff text-danger">
                                        -38
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Los Angeles Kings
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        46
                                    </td>
            <td class="losses">
                                        24
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.575
                                    </td>

            <td class="gf">
                                        340
                                    </td>
            <td class="ga">
                                        254
                                    </td>

            <td class="diff text-success">
                                        86
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Minnesota North Stars
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        27
                                    </td>
            <td class="losses">
                                        39
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.338
                                    </td>

            <td class="gf">
                                        256
                                    </td>
            <td class="ga">
                                        266
                                    </td>

            <td class="diff text-danger">
                                        -10
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Montreal Canadiens
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        39
                                    </td>
            <td class="losses">
                                        30
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.487
                                    </td>

            <td class="gf">
                                        273
                                    </td>
            <td class="ga">
                                        249
                                    </td>

            <td class="diff text-success">
                                        24
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        New Jersey Devils
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        32
                                    </td>
            <td class="losses">
                                        33
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.4
                                    </td>

            <td class="gf">
                                        272
                                    </td>
            <td class="ga">
                                        264
                                    </td>

            <td class="diff text-success">
                                        8
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        New York Islanders
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        25
                                    </td>
            <td class="losses">
                                        45
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.312
                                    </td>

            <td class="gf">
                                        223
                                    </td>
            <td class="ga">
                                        290
                                    </td>

            <td class="diff text-danger">
                                        -67
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        New York Rangers
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        36
                                    </td>
            <td class="losses">
                                        31
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.45
                                    </td>

            <td class="gf">
                                        297
                                    </td>
            <td class="ga">
                                        265
                                    </td>

            <td class="diff text-success">
                                        32
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Philadelphia Flyers
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        33
                                    </td>
            <td class="losses">
                                        37
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.412
                                    </td>

            <td class="gf">
                                        252
                                    </td>
            <td class="ga">
                                        267
                                    </td>

            <td class="diff text-danger">
                                        -15
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Pittsburgh Penguins
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        41
                                    </td>
            <td class="losses">
                                        33
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.512
                                    </td>

            <td class="gf">
                                        342
                                    </td>
            <td class="ga">
                                        305
                                    </td>

            <td class="diff text-success">
                                        37
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Quebec Nordiques
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        16
                                    </td>
            <td class="losses">
                                        50
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.2
                                    </td>

            <td class="gf">
                                        236
                                    </td>
            <td class="ga">
                                        354
                                    </td>

            <td class="diff text-danger">
                                        -118
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        St. Louis Blues
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        47
                                    </td>
            <td class="losses">
                                        22
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-success">
                                        0.588
                                    </td>

            <td class="gf">
                                        310
                                    </td>
            <td class="ga">
                                        250
                                    </td>

            <td class="diff text-success">
                                        60
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Toronto Maple Leafs
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        23
                                    </td>
            <td class="losses">
                                        46
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.287
                                    </td>

            <td class="gf">
                                        241
                                    </td>
            <td class="ga">
                                        318
                                    </td>

            <td class="diff text-danger">
                                        -77
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Vancouver Canucks
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        28
                                    </td>
            <td class="losses">
                                        43
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.35
                                    </td>

            <td class="gf">
                                        243
                                    </td>
            <td class="ga">
                                        315
                                    </td>

            <td class="diff text-danger">
                                        -72
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Washington Capitals
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        37
                                    </td>
            <td class="losses">
                                        36
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.463
                                    </td>

            <td class="gf">
                                        258
                                    </td>
            <td class="ga">
                                        258
                                    </td>

            <td class="diff text-success">
                                        0
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Winnipeg Jets
                                    </td>
            <td class="year">
                                        1990
                                    </td>
            <td class="wins">
                                        26
                                    </td>
            <td class="losses">
                                        43
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.325
                                    </td>

            <td class="gf">
                                        260
                                    </td>
            <td class="ga">
                                        288
                                    </td>

            <td class="diff text-danger">
                                        -28
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Boston Bruins
                                    </td>
            <td class="year">
                                        1991
                                    </td>
            <td class="wins">
                                        36
                                    </td>
            <td class="losses">
                                        32
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.45
                                    </td>

            <td class="gf">
                                        270
                                    </td>
            <td class="ga">
                                        275
                                    </td>

            <td class="diff text-danger">
                                        -5
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Buffalo Sabres
                                    </td>
            <td class="year">
                                        1991
                                    </td>
            <td class="wins">
                                        31
                                    </td>
            <td class="losses">
                                        37
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.388
                                    </td>

            <td class="gf">
                                        289
                                    </td>
            <td class="ga">
                                        299
                                    </td>

            <td class="diff text-danger">
                                        -10
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Calgary Flames
                                    </td>
            <td class="year">
                                        1991
                                    </td>
            <td class="wins">
                                        31
                                    </td>
            <td class="losses">
                                        37
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.388
                                    </td>

            <td class="gf">
                                        296
                                    </td>
            <td class="ga">
                                        305
                                    </td>

            <td class="diff text-danger">
                                        -9
                                    </td>

        </tr>

        <tr class="team">
            <td class="name">
                                        Chicago Blackhawks
                                    </td>
            <td class="year">
                                        1991
                                    </td>
            <td class="wins">
                                        36
                                    </td>
            <td class="losses">
                                        29
                                    </td>
            <td class="ot-losses">
            </td>

            <td class="pct text-danger">
                                        0.45
                                    </td>

            <td class="gf">
                                        257
                                    </td>
            <td class="ga">
                                        236
                                    </td>

            <td class="diff text-success">
                                        21
                                    </td>

        </tr>

    </tbody>
</table>

In [109]:
titles= soup.find_all('th')

In [110]:
titles

[<th>
                             Team Name
                         </th>,
 <th>
                             Year
                         </th>,
 <th>
                             Wins
                         </th>,
 <th>
                             Losses
                         </th>,
 <th>
                             OT Losses
                         </th>,
 <th>
                             Win %
                         </th>,
 <th>
                             Goals For (GF)
                         </th>,
 <th>
                             Goals Against (GA)
                         </th>,
 <th>
                             + / -
                         </th>]

In [106]:
titles_table = [titles.text.strip() for titles in titles]

In [107]:
print (titles_table )

['Team Name', 'Year', 'Wins', 'Losses', 'OT Losses', 'Win %', 'Goals For (GF)', 'Goals Against (GA)', '+ / -']

In [130]:
import pandas as pd

In [131]:
df= pd.DataFrame(columns = titles_table )

In [113]:
df

Empty DataFrame
Columns: [Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -]
Index: []

In [148]:
column_data = 'table'[0].find('tr')

In [147]:
for row in column_data:
    row_data = row.find_all('td')
    print(row.find('td'))
    titles_table = [title.text.strip() for data in row_data]

TypeError: 'int' object is not iterable

In [149]:
table = soup.find_all('table')          # get all tables
column_data = table[0].find_all('tr')   # get all rows from the first table

for row in column_data:
    row_data = row.find_all('td')
    titles_table = [data.text.strip() for data in row_data]
    print(titles_table)

[]
['Boston Bruins', '1990', '44', '24', '', '0.55', '299', '264', '35']
['Buffalo Sabres', '1990', '31', '30', '', '0.388', '292', '278', '14']
['Calgary Flames', '1990', '46', '26', '', '0.575', '344', '263', '81']
['Chicago Blackhawks', '1990', '49', '23', '', '0.613', '284', '211', '73']
['Detroit Red Wings', '1990', '34', '38', '', '0.425', '273', '298', '-25']
['Edmonton Oilers', '1990', '37', '37', '', '0.463', '272', '272', '0']
['Hartford Whalers', '1990', '31', '38', '', '0.388', '238', '276', '-38']
['Los Angeles Kings', '1990', '46', '24', '', '0.575', '340', '254', '86']
['Minnesota North Stars', '1990', '27', '39', '', '0.338', '256', '266', '-10']
['Montreal Canadiens', '1990', '39', '30', '', '0.487', '273', '249', '24']
['New Jersey Devils', '1990', '32', '33', '', '0.4', '272', '264', '8']
['New York Islanders', '1990', '25', '45', '', '0.312', '223', '290', '-67']
['New York Rangers', '1990', '36', '31', '', '0.45', '297', '265', '32']
['Philadelphia Flyers', '1990', '33', '37', '', '0.412', '252', '267', '-15']
['Pittsburgh Penguins', '1990', '41', '33', '', '0.512', '342', '305', '37']
['Quebec Nordiques', '1990', '16', '50', '', '0.2', '236', '354', '-118']
['St. Louis Blues', '1990', '47', '22', '', '0.588', '310', '250', '60']
['Toronto Maple Leafs', '1990', '23', '46', '', '0.287', '241', '318', '-77']
['Vancouver Canucks', '1990', '28', '43', '', '0.35', '243', '315', '-72']
['Washington Capitals', '1990', '37', '36', '', '0.463', '258', '258', '0']
['Winnipeg Jets', '1990', '26', '43', '', '0.325', '260', '288', '-28']
['Boston Bruins', '1991', '36', '32', '', '0.45', '270', '275', '-5']
['Buffalo Sabres', '1991', '31', '37', '', '0.388', '289', '299', '-10']
['Calgary Flames', '1991', '31', '37', '', '0.388', '296', '305', '-9']
['Chicago Blackhawks', '1991', '36', '29', '', '0.45', '257', '236', '21']

In [151]:
length =  len(df)
df.loc[length] = titles_table

In [152]:
print(titles_table)

['Chicago Blackhawks', '1991', '36', '29', '', '0.45', '257', '236', '21']

In [159]:
for row in column_data[1:]:
    row_data = row.find_all('td')
individual_row_data = [data.text.strip() for data in row_data]
length = len(df)
df.loc[length]= individual_row_data

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Chicago Blackhawks,1991,36,29,,0.45,257,236,21
1,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

In [ ]:
df.to_csv(r'/Users/apple/Library/CloudStorage/OneDrive-Personal/Class Document/2026 05 May/Data Analytic Essential/winnerfilename.csv',index=False)